name: Build and Deploy Multiple Sites

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # portfolio のビルド
      - name: Install dependencies portfolio
        run: npm install
        working-directory: portfolio

      - name: Build portfolio
        run: npm run build
        working-directory: portfolio

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./portfolio/dist
          destination_dir: portfolio